# Generated by Django 4.2.1 on 2023-06-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_de_nacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('fecha_de_alta', models.DateField()),
                ('domicilio', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
